---
title: "Lecture 8"
output:
  html_document:
    df_print: paged
editor_options:
  chunk_output_type: inline
---



```{r}

library(tidyverse)

myname <- "cato"

paste("My name is",myname)

```

```{r}

x <- seq(-5, 5, 0.01)
y <- -5*x**2 + x + 3 
df <- tibble(x = x, y = y)

title <- paste0("The maximum y-value of the curve is: \n",max(y))

ggplot(df, aes(x = x, y = y)) + 
  geom_line() + 
  labs(title = title)

```

```{r}
vals <- rnorm(1000)

sprintf('The mean is %.3f and the standard deviation is %.3f', mean(vals), sd(vals))
```


```{r}

library(httr)
library(jsonlite)
library(tidyverse)
library(lubridate)


```


```{r}
r <- GET('https://api.carbonintensity.org.uk/intensity')
names(r)
r
```

```{r}

# Parse the results from JSON 
parsed <- fromJSON(content(r, 'text'))

class(parsed)


```
```{r}
print(names(parsed$data))
print(names(parsed$data$intensity))
```

We can use `unnest()` to flatten this to a single, unnest data frame wiht 5 columns.

```{r}
# Unnest the intensity data 
df <- parsed$data %>% unnest(cols = intensity)
df
```
```{r}
get_carbon_intensity <- function(){
  r <- GET('https://api.carbonintensity.org.uk/intensity')
  parsed <- fromJSON(content(r, 'text'))
  df <- parsed$data %>% unnest(cols = intensity)
  return(df)
}


get_carbon_intensity()

```
```{r}
date1 <- "2020-10-08"
date2 <- "2020-10-09"
co2_intensity_data <- function(date1,date2){
  #url <- sprintf('https://api.carbonintensity.org.uk/intensity/%s/%s',date1,date2)
  url <- paste0('https://api.carbonintensity.org.uk/intensity/',date1,"/",date2)
  r <- GET(url)
  parsed <- fromJSON(content(r, 'text'))
  df <- parsed$data %>% unnest(cols = intensity)
  return(df)
  
}

co2_intensity_data("2021-01-01","2021-01,08")


```
```{r}

avg_carbon_intensity_past_week <- function(){
  d1 <- today()-days(7)
  d2 <- today()
  
  data <- co2_intensity_data(d1,d2)
  
  return(mean(data$actual))
  
}

avg_carbon_intensity_past_week()

```
```{r}
max_co2_intensity_past_week <- function(){
    # Date 7 days ago
  d1 <- today() - days(7)
  d2 <- today()
  
  # Request and parse data
  data <- co2_intensity_data(d1, d2)
  
  # The maximum intensity
  max_intensity <- max(data$actual)
  
  # Filter the data and extract the period of maximum intensity
  # (we use the beginning of the period (`from`))
  max_period <- data %>% 
    filter(actual == max_intensity) %>% 
    pull(from)
    
  return(c(max_intensity, max_period))
}

result <- max_co2_intensity_past_week()
result

```


```{r}

url <- sprintf('http://datapoint.metoffice.gov.uk/public/data/val/wxfcs/all/json/sitelist?key=%s', api_key)


r <- GET(url)

sitelist <- fromJSON(content(r, 'text')) 
sitelist <- sitelist$Locations$Location %>% tibble()
```

```{r}

sitelist %>% filter(name == "Land's End")

location_id <- '352205'

url <- sprintf('http://datapoint.metoffice.gov.uk/public/data/val/wxfcs/all/json/%s?res=3hourly&key=%s', location_id, API_KEY)

r <- GET(url)

data <- fromJSON(content(r, 'text'))




```

